name: Test and Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: python -m pytest -q
      env:
        PYTHONPATH: .

    - name: Setup SSH known hosts
      run: |
        mkdir -p ~/.ssh
        echo "Host *" > ~/.ssh/config
        echo "    StrictHostKeyChecking no" >> ~/.ssh/config
        chmod 600 ~/.ssh/config

    - name: Save private key
      run: echo "${{ secrets.EC2_SSH_KEY }}" > ./key.pem && chmod 600 ./key.pem

    - name: Test SSH connection
      run: ssh -v -i ./key.pem ubuntu@65.1.136.125
      env:
        SSH_AUTH_SOCK: ""
      shell: bash

    - name: Copy app.py to EC2
      uses: appleboy/scp-action@v0.1.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "app.py"
        target: "/home/${{ secrets.EC2_USER }}/CICD-Pipeline/"

    - name: Restart app on EC2
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          pkill -f app.py || true
          nohu
