name: CI/CD - Python Calculator to EC2

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest -q

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          source: "."
          target: "~/CICD-Practice"

      - name: SSH and deploy on EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/CICD-Practice
            python3 -m venv venv || true
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            sudo cp deploy/calculator.service /etc/systemd/system/calculator.service || true
            sudo systemctl daemon-reload
            sudo systemctl enable --now calculator.service
            sudo systemctl restart calculator.service || true
            sudo journalctl -u calculator.service --no-pager -n 50
